# These are supported funding model platforms

github: ['mbordash']
custom: ['https://www.blockchain.com/explorer/addresses/btc/bc1qceag5889jc65q9ef4ew2skr38fd0w4kfyj0vvr','https://etherscan.io/address/0xAdfA71C05Aef5fa786e8E7484784A2cB0eb39358','https://solscan.io/account/HjSJR8xGc1NbB3eULRUYC5EjZL6UpRJqBrtqFmhz8hi9']
